### ISSUE TITLE
Double tag entries

### ISSUE THREAD

**Issue by DW-rocks** [LotarProject/dokuwiki-template-bootstrap3#135]
I have created a Blog with DW + blog-plugin and use the bootstrap3-theme. On my blog-page I have the used tags listed on top of the page but some entries show more than one time (see picture). Is this a bug or did I do something wrong?
<img width="1044" alt="bildschirmfoto 2016-01-20 um 12 11 23" src="https://cloud.githubusercontent.com/assets/4059641/12447208/f536a97e-bf6e-11e5-8986-52867ca38227.png">

**Comment by LotarProject** [comment]
Hi! You have a website to see this issue ?

**Comment by DW-rocks** [comment]
Hi! I sent you a mail with the link. Thx!

**Comment by LotarProject** [comment]
Hi! Fixed in develop branch.

**Comment by DW-rocks** [comment]
Thank you very much for your really quick work! 
Nevertheless I still see the double entries (changed the plugin.js with your changes from the dev branch)

**Comment by LotarProject** [comment]
Can you purge the JS cache (via http://<dokuwiki>/lib/exe/js.php?purge) ?

At your disposal,
Joseph

**Comment by DW-rocks** [comment]
Done.

Now the tags aren't located at the top of the page anymore. I only see the tags per blog-post. Is this supposed to be like that and I should insert some kind of tag cloud to get an overview?

Thank's for your help!

**Comment by LotarProject** [comment]
It's correct. This patch don't move the tags presents inside the page (or portion of page) included with Include Plugin.

Joseph
