### ISSUE TITLE
The footer is not sticky

### ISSUE THREAD

**Issue by lifehome** [LotarProject/dokuwiki-template-bootstrap3#415]
### Description

The footer is not sticky.

### Steps to reproduce

1. Install Dokuwiki
2. Install and activate Bootstrap 3 template
3. Go to a new empty page, and see the not so sticky footer.

**Expected behavior:**
I expect it to stick.

**Actual behavior:**
It doesn't.

### Versions

* [Bootstrap3 Template] 2018-02-16
* [DokuWiki] 2018-04-22b "Greebo"
* [Plugins]
* [Browser]

### Screenshots or Logs
> ---
> 
> ![image](https://user-images.githubusercontent.com/1886237/56638930-f3f1f900-66a1-11e9-866a-481470569838.png)
> 
> ---

### Sample page or snippet
https://wiki.toughlife.info/hahaha

**Comment by LotarProject** [comment]
Hi @lifehome,
Thanks for reporting this issue.

I have corrected this behavior on develop and upcoming version of template.

At your disposal,
Joseph

**Comment by lifehome** [comment]
May I ask when will be the next version release? Can't wait to get this fixed :D

**Comment by lifehome** [comment]
@LotarProject Sorry but it is not fixed, please check it out on:
https://testwiki.toughlife.info/hahaha?purge=true

This subdomain is pulling the develop branch directly from GitHub, so it should be up-to-date with the repo.

**Comment by LotarProject** [comment]
Hi @lifehome,
i hope the last commit is the final solution :)

Joseph

**Comment by lifehome** [comment]
Hi Joseph, 

I have tested it out, and it works great! However, may I ask when will these changes merged into master? We are a bit worried on using the developer branch directly.

Regards,
Ivan

**Comment by LotarProject** [comment]
I Ivan,

Thanks for your testing.

The changes will be merged into master this or next week (now i'm retesting all template functionalities).

Stay tuned!

Joseph
